version: 0.0
os: linux
files:
  - source: /
    destination: /src/
hooks:
  ApplicationStart:
    - location: scripts/npm_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/npm_stop.sh
      timeout: 300
      runas: root
