version: 0.1

phases:
  install:
    commands:
        - sudo apt update
        - curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
        - sudo apt install -y nodejs
        - sudo apt -y --force-yes install npm
        - echo installing source NPM dependency
        - npm ci
  test:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm test
  start:
    commands:
      - echo Build completed on `date`
      - npm start
      
artifacts:
  files:
    - src/App.cs
    - src/App.js
    - src/App.test.js
    - src/index.css
    - src/index.js
    - src/logo.svg
    - src/setupTests.js
    - scripts/npm_start.sh
    - scripts/npm_stop.sh