version: 0.1

phases:
  install:
    commands:
        - sudo apt update
        - sudo apt -y --force-yes install nodejs npm
        - echo installing source NPM dependency
        - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
      - npm start
      
artifacts:
  files:
    - src/App.cs
    - src/App.js
    - src/App.test.js
    - src/index.css
    - src/index.js
    - src/logo.svg
    - src/setupTests.js
    - scripts/npm_start.sh
    - scripts/npm_stop.sh