version: 0.2

phases:
  pre-build:
    commands:
        # - aws codeartifact login --tool npm --domain my_domain --domain-owner 111122223333 --repository my_repo
        - dnf module install nodejs:12
        - echo checking node is there?
        - node -v
  build:
    commands:
      - echo Build started on `date`
      - echo installing source NPM dependency
      - npm install
      - echo Running tests
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo starting app
      - npm start
      
artifacts:
  files:
    - src/App.cs
    - src/App.js
    - src/App.test.js
    - src/index.css
    - src/index.js
    - src/logo.svg
    - src/setupTests.js
    - scripts/npm_start.sh
    - scripts/npm_stop.sh