version: 0.2

phases:
  pre_build:
    commands:
      - echo checking node is there?
      - node -v
  build:
    commands:
      - echo Build started on `date`
      - echo installing source NPM dependency
      - npm install
      - echo Running tests
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo starting app
      - npm start
      
artifacts:
  files:
    - src/App.cs
    - src/App.js
    - src/App.test.js
    - src/index.css
    - src/index.js
    - src/logo.svg
    - src/setupTests.js
    - scripts/npm_start.sh
    - scripts/npm_stop.sh